window.JEUFREX_BOOKS=[
{title:'Seul’de Bir Yaz',genre:'K-Drama',icon:'🎬',color:'#e85b9a',desc:'Seul’de bir okulun medya kulübünde dört gencin dostluk, okul hayatı ve gelecek hayalleriyle büyüdüğü sıcak dizi tadında hikâye.',chars:['Seo-jin','Min-ho','Yuna','Dae-hyun'],beats:['kulüp odasında yeni bir fikir buldu','yağmur altında eski bir not keşfetti','okul festivalinin planını değiştirdi','arkadaşlarının desteğini fark etti','bir aile konuşmasından cesaret aldı','kameranın arkasında önemli bir karar verdi']},
{title:'Koridor 17',genre:'Korku / Gerilim',icon:'🕯️',color:'#633e86',desc:'Kullanılmayan okul binasında her gece aynı saatte yanan ışığın ardındaki sırrı çözmeye çalışan üç arkadaş.',chars:['Ece','Mert','Bora'],beats:['koridorda aynı sesi yeniden duydu','duvardaki eski numarayı fark etti','güvenlik kayıtlarında tuhaf bir ayrıntı buldu','arkadaşına işaret ederek sessizce ilerledi','kilitli kapının ardındaki planı çözdü','gerçeğin sandığından farklı olduğunu anladı']},
{title:'Mahallede Bir Salı',genre:'Türk Komedi',icon:'🧿',color:'#e28b35',desc:'Ankara’da bir mahallede apartman toplantıları, yanlış anlaşılmalar ve çay sohbetleri arasında kopan kahkaha tufanı.',chars:['Emre','Sude','Kaan','Nermin Teyze'],beats:['apartman toplantısında yanlış dosyayı açtı','çay tepsisinin peşinden koştu','komşulara yeni planını anlattı','asansörde komik bir tesadüfle karşılaştı','mahalle grubundaki mesajı yanlış anladı','herkesin aynı şeye güldüğünü fark etti']},
{title:'Fırtınanın Ötesi',genre:'Macera',icon:'⛵',color:'#1d8eae',desc:'Kayıp deniz fenerinin koordinatlarını taşıyan haritanın peşindeki küçük araştırma ekibinin zamana karşı yarışı.',chars:['Ada','Kerem','Lara'],beats:['haritanın ilk parçasını buldu','kayalıklarda gizli işareti takip etti','teknenin rotasını değiştirdi','fenerden gelen ışığı fark etti','fırtınanın arasında yeni bir geçit keşfetti','haritanın neden saklandığını anladı']},
{title:'Ayna Ormanı',genre:'Fantastik',icon:'🪞',color:'#7650b5',desc:'Ağaçların arasında büyüyen aynalar farklı ihtimalleri gösterir; Nora doğru yolu seçimleriyle bulmaya çalışır.',chars:['Nora','Aras','Lio'],beats:['aynada başka bir ihtimali gördü','orman taşındaki sembolü çözdü','arkadaşlarının sesini uzaktan duydu','yanlış yolu seçtiğini fark edip geri döndü','iki aynanın aynı anda parladığını gördü','kendi kararının kapıyı açtığını anladı']},
{title:'Mars’a Son Tren',genre:'Bilim Kurgu',icon:'🚀',color:'#c35b4b',desc:'Mars kolonisine giden son tren kalkmak üzereyken genç mühendis Lina sistemdeki kritik bir hatayı fark eder.',chars:['Lina','Eren','Mika'],beats:['kontrol panelindeki küçük hatayı gördü','istasyon planını yeniden çizdi','tren görevlileriyle çözüm aradı','kayıt sisteminde eski bir mesaj buldu','son dakika testini başarıyla tamamladı','yolculuğun gerçek amacını öğrendi']},
{title:'Saatçi ve 13. Oda',genre:'Gizem',icon:'🕰️',color:'#b78a45',desc:'Eski saatçi dükkânında görünmeyen bir oda vardır. İki arkadaş, değişen dükkân planının sırrını araştırır.',chars:['Defne','Atlas','Rauf Usta'],beats:['duvarda yeni bir kapı çizgisi fark etti','eski saatin içindeki notu buldu','dükkânın planını karşılaştırdı','13 sayısının tekrarını fark etti','ustanın anlattığı eski hikâyeyi dinledi','odanın sırrını çözmek için parçaları birleştirdi']},
{title:'Son Düdük',genre:'Spor',icon:'🏀',color:'#3f83d0',desc:'Okul takımının finaline günler kala oyuncular kazanmanın yanında takım olmayı da öğrenir.',chars:['Yiğit','Mina','Can','Selin'],beats:['antrenmanda yeni bir taktik denedi','takım arkadaşının güçlü yanını keşfetti','son saniye planını hazırladı','yenilgiden sonra yeniden çalıştı','koçun tavsiyesini uyguladı','final öncesi herkes birbirine güvendi']},
{title:'İstanbul 1923',genre:'Tarih',icon:'🚂',color:'#9a7041',desc:'Eski bir günlük, Cumhuriyetin ilk yıllarındaki İstanbul’da yaşayan bir ailenin umutlarını ve değişen şehri anlatır.',chars:['Nuri','Zehra','Mehmet Efendi'],beats:['günlükte yeni bir tarih okudu','sokağın değişen yüzünü gözlemledi','ailesiyle gelecek hakkında konuştu','eski bir fotoğrafın arkasındaki yazıyı çözdü','şehirdeki yeni bir gelişmeyi öğrendi','günün sonunda umudunu deftere yazdı']},
{title:'Bir Defter Dolusu Gün',genre:'Günlük Yaşam',icon:'📓',color:'#7b6ee8',desc:'Bir öğrencinin eğitim yılı boyunca tuttuğu defter; sınavları, arkadaşlığı, aileyi ve küçük zaferleri sıcak bir dille anlatır.',chars:['Duru','İpek','Mert'],beats:['günün planını defterine yazdı','beklemediği bir başarı yaşadı','arkadaşından önemli bir tavsiye aldı','zor bir soruyu sonunda çözdü','evde ailesiyle güzel bir akşam geçirdi','gece öğrendiği şeyi kendi cümleleriyle özetledi']}
];
JEUFREX_BOOKS.forEach((b,i)=>{b.id=i;b.chapters=[1,2,3].map(n=>({number:n,title:n===1?'Başlangıç':n===2?'Dönüm Noktası':'Yeni Bir Yol',published:n===1,pages:Array.from({length:50},(_,p)=>{const a=b.chars[p%b.chars.length],c=b.chars[(p+1)%b.chars.length],beat=b.beats[(p+n+p)%b.beats.length];const starts=['Sabahın ilk ışıklarıyla hikâye yeniden hareketlendi.','O gün her şey normal başlayacak gibiydi.','Bir süre sessizlik oldu ve herkes ayrıntıları düşünmeye başladı.','Tam o anda beklenmedik bir bağlantı ortaya çıktı.','Gün ilerledikçe küçük ayrıntılar büyük bir anlam kazandı.'];let text=`${starts[(p+n)%starts.length]} ${a}, ${beat}. ${c} yanında durup notları dikkatle inceledi. Önceki sayfalarda yaşananların bugünkü kararı etkilediğini ikisi de biliyordu. `;if(p%4===0)text+=`“Bir adım daha düşünelim,” dedi ${a}. Masadaki bilgiler yeniden sıralanınca daha önce fark edilmeyen bir ayrıntı ortaya çıktı. `;if(p%7===0)text+=`${b.chars[(p+2)%b.chars.length]} yeni fikrini paylaştı ve herkes kısa bir süre sustu. `;if(p===49)text+='Bölümün sonunda herkes aynı noktada birleşti: sıradaki adım, hikâyenin şimdiye kadarki en önemli kararı olacaktı.';return{title:`Sayfa ${p+1}`,text}})}))});
